### ISSUE TITLE
installer issue

### ISSUE THREAD

**Issue by nasserman** [ignitedcms/ignitedcms#1]
hey, i think there is a beautiful things there :P but i failed to install ignitedcms,
this is not an issue maybe,
one, in localhost i didn't defined any password for DB root user
two, on my shared hosting, i have a blank DB (name.length < 10 and name.does_not_contains_numbers !!) but in first step of  installation i get this message : 
Oh Dear! Make sure database name contains only letters!  all databases on my hosting are prefixed by rahbordi_ ...
why database configuration is such hard?

**Comment by gopu18** [comment]
hello,
Could you please provide the db dump with initial set of data?

**Comment by nasserman** [comment]
my DB is empyt, can i import ignitedcms.sql and set database info in /application/config/database.config?

**Comment by ignitedcms** [comment]
Installation only works with installer, Tested on PHP version 5.6 - 7.0.8.

You cannot do a manual install as it stands
